name: Create Release
on:
  workflow_dispatch:    # 添加这个支持手动触发

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build x86 Binary
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          cross build --release --target x86_64-unknown-linux-gnu
      - name: Build ARM Binary
        run: |
          cross build --release --target aarch64-unknown-linux-gnu
      - name: Create Checksum
        run: |
          mv target/x86_64-unknown-linux-gnu/release/downloader downloader_x86
          mv target/aarch64-unknown-linux-gnu/release/downloader downloader_arm
          sha256sum downloader_x86 > x86_checksum.txt
          sha256sum downloader_arm > arm_checksum.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: |
            downloader_x86
            downloader_arm
            x86_checksum.txt
            arm_checksum.txt
